---
- hosts: localhost
  gather_facts: yes
  pre_tasks:
    - setup:
        gather_subset: "min"
  become: yes
  tasks:

 - name: include a task amz2
    include_tasks: amz.yml
    when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"
    tags:
      - always
